version: "3"
services:
  treasury:
    stdin_open: true
    ports:
      - 3000:3000
      - 3001:3001

    environment:
      - USER_DATABASE_FILE_PATH=/app/persist/databases/userdata.db
      - USER_FILE_STORAGE_PATH=/app/persist/userfiles
      - USER_UPLOAD_TEMPORARY_STORAGE_PATH=/app/persist/uploads
      - SECURE_COOKIES=false

    volumes:
      - ./persist:/app/persist
    image: treasury
    restart: unless-stopped
