name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Install additional target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --manifest-path=backend/Cargo.toml --release --target x86_64-unknown-linux-gnu

      - name: Move executable
        run: cp backend/target/x86_64-unknown-linux-gnu/release/backend .

      - name: Release
        uses: softprops/action-gh-release@v2
